dateModified: 1586224621
email:
  fromEmail: $EMAIL_SYSTEM_EMAIL_ADDRESS
  fromName: $EMAIL_SENDER_NAME
  template: ''
  transportSettings: null
  transportType: craft\mail\transportadapters\Sendmail
fieldGroups:
  31591f3c-b2da-4ef4-877a-4756a80b1d50:
    name: Common
plugins:
  cp-field-inspect:
    schemaVersion: 1.0.0
  guide:
    schemaVersion: 2.0.0
  image-optimize:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  image-resizer:
    schemaVersion: 2.0.0
  redactor:
    schemaVersion: 2.3.0
  seomatic:
    enabled: true
    schemaVersion: 3.0.8
    settings:
      addHrefLang: true
      addXDefaultHrefLang: true
      cpTitlePrefix: '⚙ '
      devModeCpTitlePrefix: '&#x1f6a7;⚙ '
      devModeTitlePrefix: '&#x1f6a7; '
      displayAnalysisSidebar: true
      displayPreviewSidebar: true
      environment: $ENVIRONMENT
      generatorEnabled: true
      headersEnabled: true
      lowercaseCanonicalUrl: '1'
      maxDescriptionLength: 155
      maxTitleLength: 70
      pluginName: SEO
      regenerateSitemapsAutomatically: true
      renderEnabled: true
      separatorChar: '|'
      sidebarDisplayPreviewTypes:
        - google
        - twitter
        - facebook
      siteGroupsSeparate: '1'
      siteUrlOverride: ''
      sitemapsEnabled: true
      socialMediaPreviewTarget: true
  typedlinkfield:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
siteGroups:
  9c94fc46-354f-4e2d-b28c-a884a5ea683c:
    name: $SITE_NAME
sites:
  1a456e16-c64d-4f15-a96f-908626ede7a4:
    baseUrl: $DEFAULT_SITE_URL
    handle: default
    hasUrls: true
    language: en-US
    name: $SITE_NAME
    primary: true
    siteGroup: 9c94fc46-354f-4e2d-b28c-a884a5ea683c
    sortOrder: 1
system:
  edition: pro
  live: true
  name: $SITE_NAME
  schemaVersion: 3.4.10
  timeZone: America/New_York
users:
  allowPublicRegistration: false
  defaultGroup: null
  groups:
    0e71a30c-d2bc-4643-86e8-4ef88987fdf0:
      handle: seoEditor
      name: 'SEO Editor'
      permissions:
        - accessplugin-guide
        - accessplugin-seomatic
        - accesscp
        - 'seomatic:dashboard'
        - 'seomatic:global-meta:general'
        - 'seomatic:global-meta:twitter'
        - 'seomatic:global-meta:facebook'
        - 'seomatic:global-meta:robots'
        - 'seomatic:global-meta:humans'
        - 'seomatic:global-meta:ads'
        - 'seomatic:global-meta'
        - 'seomatic:content-meta:general'
        - 'seomatic:content-meta:twitter'
        - 'seomatic:content-meta:facebook'
        - 'seomatic:content-meta:sitemap'
        - 'seomatic:content-meta'
        - 'seomatic:site-settings:identity'
        - 'seomatic:site-settings:creator'
        - 'seomatic:site-settings:social'
        - 'seomatic:site-settings:sitemap'
        - 'seomatic:site-settings:miscellaneous'
        - 'seomatic:site-settings'
        - 'seomatic:tracking-scripts:googleanalytics'
        - 'seomatic:tracking-scripts:gtag'
        - 'seomatic:tracking-scripts:googletagmanager'
        - 'seomatic:tracking-scripts:facebookpixel'
        - 'seomatic:tracking-scripts:linkedininsight'
        - 'seomatic:tracking-scripts:hubspot'
        - 'seomatic:tracking-scripts'
        - 'seomatic:plugin-settings'
    15c02845-ac7d-4a42-baaf-b528aa2798bb:
      handle: contentEditor
      name: 'Content Editor'
      permissions:
        - accessplugin-communicator
        - accessplugin-guide
        - accesscp
        - registerusers
        - 'assignusergroup:46a24753-03de-403c-96c4-568e5885df44'
        - assignusergroups
        - editusers
        - 'createentries:8780f4ca-f1e9-4eab-8c64-2c668a7b346e'
        - 'publishentries:8780f4ca-f1e9-4eab-8c64-2c668a7b346e'
        - 'deleteentries:8780f4ca-f1e9-4eab-8c64-2c668a7b346e'
        - 'publishpeerentries:8780f4ca-f1e9-4eab-8c64-2c668a7b346e'
        - 'deletepeerentries:8780f4ca-f1e9-4eab-8c64-2c668a7b346e'
        - 'editpeerentries:8780f4ca-f1e9-4eab-8c64-2c668a7b346e'
        - 'publishpeerentrydrafts:8780f4ca-f1e9-4eab-8c64-2c668a7b346e'
        - 'deletepeerentrydrafts:8780f4ca-f1e9-4eab-8c64-2c668a7b346e'
        - 'editpeerentrydrafts:8780f4ca-f1e9-4eab-8c64-2c668a7b346e'
        - 'editentries:8780f4ca-f1e9-4eab-8c64-2c668a7b346e'
        - 'publishentries:804fec4f-1997-47dc-908b-589f0b3fd640'
        - 'publishpeerentrydrafts:804fec4f-1997-47dc-908b-589f0b3fd640'
        - 'deletepeerentrydrafts:804fec4f-1997-47dc-908b-589f0b3fd640'
        - 'editpeerentrydrafts:804fec4f-1997-47dc-908b-589f0b3fd640'
        - 'editentries:804fec4f-1997-47dc-908b-589f0b3fd640'
    1de3ee0e-4424-4cd7-b8d9-fbae086a2473:
      handle: guideEditor
      name: 'Guide Editor'
      permissions:
        - accessplugin-guide
        - accesscp
        - editguides
        - setaccesspermissions
        - deleteguides
        - useorganizer
    46a24753-03de-403c-96c4-568e5885df44:
      handle: contentAuthor
      name: 'Content Author'
      permissions:
        - accessplugin-communicator
        - accessplugin-guide
        - accesscp
        - 'createentries:8780f4ca-f1e9-4eab-8c64-2c668a7b346e'
        - 'publishentries:8780f4ca-f1e9-4eab-8c64-2c668a7b346e'
        - 'deleteentries:8780f4ca-f1e9-4eab-8c64-2c668a7b346e'
        - 'publishpeerentries:8780f4ca-f1e9-4eab-8c64-2c668a7b346e'
        - 'deletepeerentries:8780f4ca-f1e9-4eab-8c64-2c668a7b346e'
        - 'editpeerentries:8780f4ca-f1e9-4eab-8c64-2c668a7b346e'
        - 'editentries:8780f4ca-f1e9-4eab-8c64-2c668a7b346e'
        - 'publishentries:804fec4f-1997-47dc-908b-589f0b3fd640'
        - 'editentries:804fec4f-1997-47dc-908b-589f0b3fd640'
    48c65c4b-8797-4301-9213-274e2037ace4:
      handle: userAdmin
      name: 'User Admin'
      permissions:
        - accessplugin-communicator
        - accessplugin-guide
        - accesscp
        - registerusers
        - moderateusers
        - assignuserpermissions
        - 'assignusergroup:46a24753-03de-403c-96c4-568e5885df44'
        - 'assignusergroup:15c02845-ac7d-4a42-baaf-b528aa2798bb'
        - 'assignusergroup:1de3ee0e-4424-4cd7-b8d9-fbae086a2473'
        - 'assignusergroup:0e71a30c-d2bc-4643-86e8-4ef88987fdf0'
        - assignusergroups
        - administrateusers
        - impersonateusers
        - editusers
        - deleteusers
  photoSubpath: ''
  photoVolumeUid: null
  requireEmailVerification: true
