name: <%- handle %>
type: php
php_version: "7.4"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns:
- <%- handle %>.test
provider: default
hooks:
  post-import-db:
  - exec: time .ddev/scripts/migrate.sh
  post-start:
  - exec: time .ddev/scripts/setup.sh
use_dns_when_possible: false
